// src/auth/dto/create-user.dto.ts
import { IsString, IsEmail, IsEnum, IsOptional } from 'class-validator';
import { UserRole, UserStatus } from 'src/users/user.entity';

export class CreateUserDto {
  @IsString()
  name: string;

  @IsEmail()
  email: string;

  @IsString()
  password: string;

  @IsEnum(UserRole)
  role: UserRole = UserRole.CUSTOMER;

  @IsEnum(UserStatus)
  status: UserStatus = UserStatus.PENDING;

  @IsOptional() // This could be optional since it is generated by the database
  createdAt?: Date;

  @IsOptional() // This could be optional since it is generated by the database
  updatedAt?: Date;
}
