// src/auth/dto/create-user.dto.ts
import { IsString, IsEmail, IsEnum, IsOptional, IsDateString } from 'class-validator';
import { UserRole, UserStatus } from 'src/common/enums/user.enum';

export class CreateUserDto {
  @IsString()
  name: string;

  @IsEmail()
  email: string;

  @IsString()
  password: string;

  @IsString()
  @IsOptional()
  username?: string;

  @IsString()
  @IsOptional()
  phoneNumber?: string;

  @IsDateString()
  @IsOptional()
  dateOfBirth?: Date;

  @IsString()
  @IsOptional()
  avatar?: string;

  @IsEnum(UserRole)
  role: UserRole = UserRole.CUSTOMER;

  @IsEnum(UserStatus)
  status: UserStatus = UserStatus.PENDING;

  @IsOptional() // This could be optional since it is generated by the database
  createdAt?: Date;

  @IsOptional() // This could be optional since it is generated by the database
  updatedAt?: Date;
}
